### ISSUE TITLE
Failed projects

### ISSUE THREAD

**Issue by lrussow** [vase4kin/TeamCityApp#197]
I really like this app. Thank you

I would like to suggest an addition. It would be great to see a list of only the recently failed projects.

**Comment by vase4kin** [comment]
Hey, @lrussow! 
Thanks for reaching me out here! Happy to hear that someone likes the app :heart: 
Let me check if it's possible to implement, not sure it is supported by Teamcity API.
I'll let you know soon, I hope within next week.
Cheers!

**Comment by vase4kin** [comment]
@lrussow hey, here's a small update. I checked the API, seems like it's possible, but it could take time to implement cause API doesn't support this out of the box. Also, it could be not that data performant. 
Anything else I could you help you with?
