### ISSUE TITLE
Cannot load builds

### ISSUE THREAD

**Issue by auricgoldfinger** [vase4kin/TeamCityApp#214]
Currently, I cannot load the builds page on the teamcity server at work. It's still version 2017.1.1, maybe that has something to do with it?

While browsing the projects, I constantly get the error page. When I tap "try again" then the subproject list loads until I open a real build configuration. Then the error page keeps coming and I cannot see which builds were failing or successful...

**Comment by vase4kin** [comment]
hey, @auricgoldfinger. Thanks for contacting me. 

What version of the app are you using? Did it happen after the update or you're new to the app?

Could you please do me a favor? On the last version, which is `1.4.1.0` I added the prompt at the bottom of the login page to try the official TeamCity server, could you please use it and tell me are you able to see builds there? Also if there's no prompt you can try to sign in to `https://teamcity.jetbrains.com/` by a guest user.

**Comment by bobbanks** [comment]
I'm having a similar problem that's likely related.  After authentication, I see the project list.  If I pull to refresh or tap on a project, I see the error page.  Works fine with `https://teamcity.jetbrains.com/` as a guest.  Running server 2018.2 (build 60925)

**Comment by vase4kin** [comment]
Hey, found the issue, still can't believe I missed it. I'll publish a new version with a fix within today or over the weekend. 

@auricgoldfinger @bobbanks thanks for reporting, guys

**Comment by auricgoldfinger** [comment]
Thank you for fixing it 😉
However, there's still a little problem. I have two build configurations, one triggers the other. The triggered one loads correctly now (thanks!) But the one that is triggering (and listening on the git server) doesn't. The app crashes when I try to open that configuration.

I sent an Android crash report, so that you can investigate

**Comment by vase4kin** [comment]
@auricgoldfinger thanks for reporting, I've released `1.4.3.1` fixing your issue, let me know how it works for you when you get the update. I hope it's the last one :)

**Comment by auricgoldfinger** [comment]
I just installed the update and it works! I tested all configurations and even restarted a build. Everything seems ok now. Many thanks!

**Comment by vase4kin** [comment]
@auricgoldfinger awesome, happy to hear that. Closing the issue.
