### ISSUE TITLE
Color icons

### ISSUE THREAD

**Issue by ZoolooDan** [vase4kin/TeamCityApp#366]
Would be really helpful if status icons would be colored. Green for success and red for failure.

**Comment by vase4kin** [comment]
Hi, @ZoolooDan! 

Thanks for coming here. Appreciated. 

It was this way before the dark theme was introduced. I decided to keep it simple. 
In order to support this, I need to have a set of colors that would work for a light and dark theme. 

Do you think that would benefit the app?

**Comment by vase4kin** [comment]
hey, @ZoolooDan!

I've added colored statutes for the build list screen. It will be available in the upcoming release, which is 1.52.4. 
Here're some screenshots:
|Light theme | Dark theme |
:-------------------------:|:-------------------------:|
![Screenshot_20201220-094053](https://user-images.githubusercontent.com/4580186/102703322-51d84900-42a8-11eb-8927-e8ec341f5818.png) | ![Screenshot_20201220-094039](https://user-images.githubusercontent.com/4580186/102703323-56046680-42a8-11eb-9f55-63970cc7db3a.png)
