### ISSUE TITLE
Show snapshot dependencies in build

### ISSUE THREAD

**Issue by munkie** [vase4kin/TeamCityApp#47]
Hi @vase4kin, i really like your app and use on daily basis to check CI build status while i'm away from computer.

But there is one thing i would like to see - its snapshot dependencies in build.

Here is a expected scenario how feature should work:

> As active and loyal app user
> I would like to be able to see build snapshot dependencies
> So in case of dependent build failure i could navigate to it and check reason of failure

> Given i start build in TC with snapshot dependencies
> When i check build status in mobile app
> Then i can see list of snapshot dependencies
> And can navigate to dependent build details

**Comment by munkie** [comment]
Great work @vase4kin. When you will release new version with this improvement ?

**Comment by vase4kin** [comment]
Thanks, @munkie. In one-two days, i'd like to add one more feature to the upcoming release. I hope it won't take any longer.
